"""
docgen_tool.py — Generate Word documents, PowerPoint presentations, and Excel files.

These are the "real deliverable" payoffs of the agentic loop.
Every generated file is written to the workspace and surfaced in the UI as a file card.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from sovereignai.tools.base import Tool, ToolResult
from sovereignai.tools.fs_tools import _validate_path


class GenDocx(Tool):
    name = "generate_docx"
    description = (
        "Generate a Word document (.docx) with sections and content. "
        "Perfect for approval notes, reports, memos, summaries."
    )
    categories = ["general", "planning", "document_qa", "vision"]
    json_schema = {
        "type": "object",
        "properties": {
            "output_path": {"type": "string",  "description": "Output .docx file path"},
            "title":       {"type": "string",  "description": "Document title"},
            "sections": {
                "type": "array",
                "description": "List of sections",
                "items": {
                    "type": "object",
                    "properties": {
                        "heading": {"type": "string"},
                        "body":    {"type": "string"},
                        "level":   {"type": "integer", "description": "Heading level 1-3"},
                    },
                    "required": ["heading", "body"],
                },
            },
            "author":   {"type": "string",  "description": "Document author (optional)"},
            "date":     {"type": "string",  "description": "Document date (optional)"},
        },
        "required": ["output_path", "title", "sections"],
    }

    def run(
        self,
        output_path: str,
        title: str,
        sections: list[dict],
        author: str | None = None,
        date: str | None = None,
    ) -> ToolResult:
        p = _validate_path(output_path)
        if p is None:
            return ToolResult.fail(f"Path '{output_path}' outside workspace.")

        try:
            from docx import Document
            from docx.shared import Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            import datetime

            doc = Document()

            # Title
            title_para = doc.add_heading(title, 0)
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

            # Metadata line
            meta_parts = []
            if author:
                meta_parts.append(f"Author: {author}")
            if date:
                meta_parts.append(f"Date: {date}")
            else:
                meta_parts.append(f"Date: {datetime.date.today().isoformat()}")
            if meta_parts:
                meta = doc.add_paragraph(" | ".join(meta_parts))
                meta.alignment = WD_ALIGN_PARAGRAPH.CENTER

            doc.add_paragraph("")  # spacing

            # Sections
            for sec in sections:
                heading_text = sec.get("heading", "")
                body_text    = sec.get("body", "")
                level        = min(max(int(sec.get("level", 1)), 1), 3)
                doc.add_heading(heading_text, level=level)
                doc.add_paragraph(body_text)

            # Footer note
            doc.add_paragraph("")
            footer = doc.add_paragraph("Generated by SovereignAI — Local models. Local data. Zero external calls.")
            footer.runs[0].italic = True

            p.parent.mkdir(parents=True, exist_ok=True)
            doc.save(str(p))
            size = p.stat().st_size
            return ToolResult.ok({
                "path": str(p),
                "size_bytes": size,
                "sections": len(sections),
            }, file_path=str(p))

        except ImportError:
            return ToolResult.fail("python-docx not installed. Run: pip install python-docx")
        except Exception as e:
            return ToolResult.fail(str(e))


class GenPptx(Tool):
    name = "generate_pptx"
    description = "Generate a PowerPoint presentation (.pptx) from a list of slides."
    categories = ["general", "planning", "vision"]
    json_schema = {
        "type": "object",
        "properties": {
            "output_path": {"type": "string", "description": "Output .pptx file path"},
            "title":       {"type": "string", "description": "Presentation title"},
            "slides": {
                "type": "array",
                "description": "List of slides",
                "items": {
                    "type": "object",
                    "properties": {
                        "title":   {"type": "string"},
                        "bullets": {"type": "array", "items": {"type": "string"}},
                        "notes":   {"type": "string", "description": "Speaker notes"},
                        "layout":  {"type": "string", "description": "title_only | bullet | blank"},
                    },
                    "required": ["title"],
                },
            },
        },
        "required": ["output_path", "title", "slides"],
    }

    def run(self, output_path: str, title: str, slides: list[dict]) -> ToolResult:
        p = _validate_path(output_path)
        if p is None:
            return ToolResult.fail(f"Path '{output_path}' outside workspace.")

        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt

            prs = Presentation()

            # Title slide
            title_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_layout)
            slide.shapes.title.text = title
            if slide.placeholders and len(slide.placeholders) > 1:
                slide.placeholders[1].text = "Generated by SovereignAI"

            # Content slides
            for s in slides:
                layout = prs.slide_layouts[1]  # Title + Content
                sl = prs.slides.add_slide(layout)
                sl.shapes.title.text = s.get("title", "")
                if s.get("bullets") and len(sl.placeholders) > 1:
                    tf = sl.placeholders[1].text_frame
                    tf.text = ""
                    for bullet in s["bullets"]:
                        p_para = tf.add_paragraph()
                        p_para.text = bullet
                        p_para.level = 0
                if s.get("notes"):
                    sl.notes_slide.notes_text_frame.text = s["notes"]

            p.parent.mkdir(parents=True, exist_ok=True)
            prs.save(str(p))
            size = p.stat().st_size
            return ToolResult.ok({
                "path": str(p),
                "size_bytes": size,
                "slides": len(slides) + 1,
            }, file_path=str(p))

        except ImportError:
            return ToolResult.fail("python-pptx not installed. Run: pip install python-pptx")
        except Exception as e:
            return ToolResult.fail(str(e))


class GenXlsx(Tool):
    name = "generate_xlsx"
    description = "Generate an Excel workbook (.xlsx) with data. Alias of sheet_create."
    categories = ["general", "planning", "spreadsheet"]
    json_schema = {
        "type": "object",
        "properties": {
            "output_path": {"type": "string", "description": "Output .xlsx file path"},
            "sheet_name":  {"type": "string", "description": "Sheet name"},
            "headers":     {"type": "array",  "items": {"type": "string"}},
            "rows":        {"type": "array",  "items": {"type": "array"}},
        },
        "required": ["output_path", "headers"],
    }

    def run(self, output_path: str, headers: list[str], rows: list[list] | None = None, sheet_name: str = "Data") -> ToolResult:
        from sovereignai.tools.sheet_tool import SheetCreate
        return SheetCreate().run(path=output_path, headers=headers, rows=rows, sheet_name=sheet_name)

